### ISSUE TITLE
Implement matching algorithms

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#217]
I recently created an API that lets programmers easily specify rules for how participants are grouped into matches (and regrouped in subsequent rounds), like perfect stranger/round robin, partner matching, zipper, "swap out 25% of participants", "switch P1 and P2", etc. But the algorithms themselves need to be implemented.

**Comment by leliel12** [comment]
after some research on the code and the documentation i have a question about issue. The idea is replace the `group_by_arrival_time` in session for something like `group_players_by: "arrival_time" ` or  `group_players_by: "round_robin" `, or the idea is for implement something like:

```python

def before_session_starts(self):
    if self.round_number > 1:
        for group in self.get_groups():
            players = group.get_players()
            players = player_sorts.round_robin(players)
            group.set_players(players)
```

**Comment by oTree-org** [comment]
My plan has been the 2nd option you describe.

**Comment by leliel12** [comment]
new draft

```python
def before_session_starts(self):
    if self.round_number > 1:
        match_players.perfect_strangers(self)
```

The idea is directly sort the groups inside the subsession `self`and if some kind of buffer is needed the match algorithm will store the data (for example previous groups for guarantee the round robin) inside a new attribute of session called `_match_buffer = {}`

The methods will be implemented in otree.match_players.py

**Comment by oTree-org** [comment]
Note that you can access the groups from previous rounds with `subsession.in_previous_rounds()`.

**Comment by leliel12** [comment]
Great

Juan BC (sent from my phone)

**Comment by leliel12** [comment]
```python
def before_session_starts(self):
    if self.round_number > 1:
        players_x_group = match_players.perfect_strangers(self)
        for group, players in zip(self.get_groups(), players_x_group):
            group.set_players(players)
```

**Comment by leliel12** [comment]
```python
def before_session_starts(self):
    if self.round_number > 1:
        self.match_players("perfect_strangers")
        for group in self.get_groups():
              # foo

```

**Comment by leliel12** [comment]
@oTree-org  What is the logic behind the "swap 25%" (the switch player 1& 2) is esentially a reverse

**Comment by oTree-org** [comment]
It was just a fictional example. We don't need to implement that.

**Comment by leliel12** [comment]
Notes sended by email:


Here are some notes on matching to help you with your implementation:

Note that each round (subsession) has a distinct set of player objects. In a 5-round game, each participant would be represented by 5 players. Each player is specific to one round. The total number of players is equal to:

(number of participants) * (number of rounds)

So, I am not sure this code would work:

@match_func("partners")
def partners(subssn):
    p_subssn = subssn.in_previous_rounds()[-1]
    return players_x_groups(p_subssn)

Because it looks like it is taking the player objects from round 1 and putting them into round 2, which would overwrite the player objects from round 2. (I may be incorrect because I did not read the code structure and decorators thoroughly).

I think this has the same issue:

@match_func("reversed", "players_reversed")
def players_reversed(subssn):
    p_subssn = subssn.in_previous_rounds()[-1]
    reversed_players_x_groups = []
    for players in players_x_groups(p_subssn):
        players_reversed = list(reversed(players))
        reversed_players_x_groups.append(players_reversed)
    return tuple(reversed_players_x_groups)


I think you don't have to use `in_previous_round`. Instead, I think you can take advantage of the fact that oTree uses partner matching by default, which means that in `before_session_starts`, the players have already been assigned into groups that match the grouping from the previous round. Then, you can permute this as you want, e.g.:

def before_session_starts(self):
    for group in self.get_groups():
        players = group.get_players()
        players.reverse()
        group.set_players(players)


However, it gets a bit more complicated if a particular algorithm needs to look at more than just the previous round (if it needs to also know N-2, N-3, etc....). Then you need to use a different technique.

**Comment by leliel12** [comment]
Note 2

Also, note that groups can have uneven size. From the docs:

    "If you need your groups to have uneven sizes (for example, 2 vs 3), you can do this: players_per_group=[2,3]; in this case, if you have a session with 15 players, the group sizes would be [2,3,2,3,2,3]"


I just added a docstring in master to otree.models.subsessions.BaseSubsession._get_players_per_group_list

Also see otree.common_internal.min_players_multiple

Chris
