### ISSUE TITLE
oTree test bots performance profiling

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#235]
Especially of test bots, which are slow e.g. with 60 participants.

**Comment by alexsanduk** [comment]
Some comments in email exchange with @leliel12 
### Email 1:
Lets talk about this code:
https://github.com/oTree-org/otree-core/blob/master/otree/test/runner.py

I rewrite entire the bot system removing threads and use in-memory
databases for performances (the old version is 900x slower than the
actual one). I was aware of some slow steps in the bot but is for
simulate the async access. IMHO this is no way to make this faster for
the nature of the problem.

Essentially the bots execute all de submit are stored into a queue,
after that to iterations occurs:

- The first one (the second in order of code (line 201)) try to
execute the submit, if  is a wait page is returned this will be added
to the another iteration.
- The second (line: 192) one try to execute all the pending submits.

If you want to make better this code Good luck :D, I have no idea how
to do that so i wish you can make the bots more fasts.

But in other hand 60 bots is a LOT of people playing!

### Email 2:
the main utility for profile is the module "timeit"
and probably the part of code i comment in the last mail is a best
place to start.

Also the last version of pycharm has a nice profiler.

More info: https://docs.python.org/2/library/profile.html
https://pypi.python.org/pypi/django-profiler/ <<<  this is also a nice
project (but i never use it in production)

**Comment by gregmuellegger** [comment]
I can recommend https://jiffyclub.github.io/snakeviz/ as a profile viewer.
You can record the performance profile for the tests like so:
```
python -m cProfile -o otree-test.profile ./otree test
```
After that finishes you can view the profile with `snakeviz otree-test.profile`.

**Comment by leliel12** [comment]
https://www.youtube.com/watch?v=DUCMjsrYSrQ <<< i take this tutorial

**Comment by leliel12** [comment]
**Method level analisis (1/3)**

- The most time taking by the test is divided by the `run_tests`

![runtest](https://cloud.githubusercontent.com/assets/299010/8149629/b5ae8ca2-12a0-11e5-8e40-96a80097732b.png)

And setup_databases

![setupdatabases](https://cloud.githubusercontent.com/assets/299010/8149630/c069795e-12a0-11e5-9b7c-dd510b378bfc.png)

**Comment by leliel12** [comment]
I changed the tittle of the issue because we need to profiles parts of the projects

**Comment by leliel12** [comment]
**Method Level Analisis 2/3**

sees from `_run_subsession_round`

- The `__call__` low level function of python is really slow

![call](https://cloud.githubusercontent.com/assets/299010/8149692/7c69014a-12a3-11e5-9282-9c26d935fb8a.png)


- `_handle_redirect` from django test framework is also slow

![handle](https://cloud.githubusercontent.com/assets/299010/8149698/b1edc77e-12a3-11e5-919f-fb15749a48d6.png)


- `get_response_method` from django is also really slow (because they resolve the middlewares and template issues)
![get_response](https://cloud.githubusercontent.com/assets/299010/8149696/9cd3a5d4-12a3-11e5-9b12-cc40f3d07fa8.png)

**Comment by leliel12** [comment]
**Method Level Analysis 3/3**

The most part of the time is used by the simulation of get and post inside django test framework.

**Method Level From File Point of View**

This is the time spend in run all the test (python + django  + all the apps + otree code).

![asfile](https://cloud.githubusercontent.com/assets/299010/8150786/ed4b10fe-12cd-11e5-9b71-1282f6fd5ea5.png)

1. The big square are the entry points (and only represent the time expended waiting for all the run
2. Te big square of the upper right is the time expended in django (the bigest) and all the installed apps
3. The small square of the bottom right is the otree code (is really an small part of the all run)

The another squares are the python built-ins libraries

Inside the otree files

![otree](https://cloud.githubusercontent.com/assets/299010/8150806/ff433f4c-12ce-11e5-86fc-ee49969f95df.png)


1. The `otree/checks` (spend most part of the time)
2. `otree/db`
3.  The *views*
4. The session.py models are one of the biggest spend of time
5. The `otree/test/client.py` the slowest because is where we execute the post and get thorught django test framework
6. The `otree/test/runner.py`

**Comment by leliel12** [comment]
**Partial Conclusions:**

- The main bottle neck inside otree as this point is the `otree/db/sessions.py` models
- The most part of the time spended inside the test framework are inside `otree/db/test/client.py` because the calls of *POST* and *GET* of the django test framework.

**Comment by leliel12** [comment]
**Stats Profiling**

- StatProf Full Output: https://gist.github.com/leliel12/2b0126d73d20fb1c441a
- Analysis: http://nbviewer.ipython.org/gist/leliel12/69c9617d89990da138e3

**Comment by leliel12** [comment]
**Conclusions**

- The *oTree Test framework* are fast as django test framework can be when it running.
- Our real bottle necks are the `otree.checks`,  `otree.db` in general and `otree.db.sessions` in particular.
