### ISSUE TITLE
CurrencyField: form widget doesn't show current value of the field

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#269]
Repro steps:

In models.py, put this in the `Player` class:

```
my_currency_field = models.CurrencyField(default=10)
```

Then, in the views.py, put this in a Page class:

```
    form_model = models.Player
    form_fields = ['my_currency_field']
```

And put this in the HTML template:

```
{% formrow form.my_currency_field %}
```

Expected: the form widget should display the current value of the ($10), as it does for integer fields
Actual: the form widget is blank

Note, the change page in the admin correctly displays the current value of the field in the form widget, it's just in oTree's ModelForms that it is wrong.

**Comment by gregmuellegger** [comment]
The commit https://github.com/oTree-org/otree-core/commit/be490a1535dd1c5a62a2bf5a542f56bc26daa2c5 contains a test and a fix.
The problem was, that the currency symbol got rendered with the money value in the html, like: `<input type="number" value="€12.34" />`. The browser didn't like this as number value and therefore ignored the value.
