### ISSUE TITLE
Django-sslify middleware and default local server

### ISSUE THREAD

**Issue by alexsanduk** [oTree-org/otree-core#300]
Currently the following is observed with Django-sslify middleware enabled in [settings.py](https://github.com/oTree-org/otree-core/blob/master/otree/settings.py#L85).
On Mac OS X the request to `http://localhost:8000` is handled securely, but not on Windows.
Hence if you are running regular server (`./otree runserver`) on Mac OS X this request fails, but not on Windows.

If this bug is specific to windows, should ssl server (`./otree runsslserver`) be the default for local deployment. Does anyone see drawbacks to such decision?

Another solution to enable middleware only if secured server is running and disable otherwise. But how to understand that we run secure server? 

Under both solutions what happens if we have secured server on Windows and user request `http://localhost:8000`.

Currently ssl is used only for publishing mturk hits via [AWS ExternalQuestion Data Structure](http://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_ExternalQuestionArticle.html).

**Comment by oTree-org** [comment]
I am currently drafting a response with a further explanation of this issue, but I need to do some more research and discussion first.

**Comment by leliel12** [comment]
probably we can make a wrapper runserver who made the better choice. And
with some flags like "--ssl" for force the ssl runserver

2015-04-08 0:03 GMT-03:00 oTree-org <notifications@github.com>:

> I am currently drafting a response with a further explanation of this
> issue, but I need to do some more research and discussion first.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oTree-org/otree-core/issues/300#issuecomment-90790221>
> .
>



-- 
Juan B Cabral

**Comment by oTree-org** [comment]
@alexsanduk and I just spoke about this and we came up with a solution we will try and see.

**Comment by oTree-org** [comment]
Currently, SSL is only needed if you are trying to publish to Mechanical Turk. MTurk embeds the oTree game as an iframe when the user is on MTurk.com. If the embedded page is not HTTPS, it will not render, as explained [here](http://stackoverflow.com/a/27385690).

We made 2 modifications to oTree to support SSL:

* added "runsslserver" app to installed_apps, so that the runsslserver management command is available. When you need the server to run as SSL, you use this instead of runserver.
* added Django-sslify middleware so that anytime a request is made to http://some-url, it gets redirected to https://some-url

By the way, runsslserver is not necessary on Heroku, because Heroku SSL support built in. If you request any URL with https:// it will handle that using SSL.

The part that is currently *not working* is trying to publish to mechanical Turk from a non-Heroku server that was started with "runserver" (non SSL version). The most common example is if I am developing locally and want to publish to the mechanical Turk sandbox for test purposes. (You can actually publish to MTurk sandbox using a server URL that only works locally. When you test your app, you browse to MTurk.com and it embeds an iframe pointing to 127.0.0.1 which happens to work if you are testing on your own server machine.)

The most extreme way to solve this problem is to make runserver always use SSL, and the launcher would open the browser to https://127.0.0.1). However, I wonder if always using SSL would complicate other parts of oTree. I think only a minority of users will be publishing to Mechanical Turk, so we do not want to inconvenience everybody else because of this.

Another solution is that if a user clicks to publish a HIT and we detect they are not in SSL mode, to tell them they need to restart the server with "runsslserver". We are attempting to write code that can check this but it is not working yet.

**Comment by alexsanduk** [comment]
Summing up SSL support is needed only for publishing hits on MTurk platform.
Following suggestion by @leliel12 we agreed on the following:
* if AWS credentials are not provided then `./otree runserver` should invoke regular django development server. In this case MTurk tab should contain instructions how to enable MTurk.
* if user has provided AWS credentials then `./otree runserver` should invoke ssl enabled server
This approach is implemented in this two commits 9bed8c8 and e60eae0.

**Comment by gregmuellegger** [comment]
Is the underlying problem, that the user won't know if it's required to use SSL?
Or that it's hard to discover if the user should open `http://localhost:8000/` or `https://localhost:8000/` in the browser?

The problem I see is that it's not possible to have the server work with HTTP and HTTPS on the same port. That way it's not possible to redirect from `http://localhost:8000/` to `https://localhost:8000/`!
See this ticket in django-ssl for more details: https://github.com/teddziuba/django-sslserver/issues/2

A simple solution to this problem might be, to more prominently show the URL of the running server in the console and opening that URL automatically in the users default browser. That way the user runs `./otree runsslserver` and it opens a new tab in the browser that shows `https://localhost:8000/`.
