### ISSUE TITLE
AUTH_LEVEL should be implemented with whitelist, not blacklist

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#303]
...so that if we implement a new page and forget to specify its auth level, it is assumed to be restricted, to prevent unwanted access.

**Comment by leliel12** [comment]
Enjoy alex look fun

**Comment by alexsanduk** [comment]
Thank you Juan, nice one.
This issue is related to #273.
Currently we have 3 levels of authorisation: `FULL, DEMO, EXPERIMENT`. In `DEBUG` mode it defaults to `FULL`. In non-`DEBUG` mode it defaults to `EXPERIMENT`. 
`EXPERIMENT` mode is the most restricted, than `DEMO` mode and the most "loose" mode is `FULL`.
Following table contains all the views ('x' indicates if login not required for access):

|Module | View Name | `EXPERIMENT`|`DEMO`|`FULL`|
|:---------------:|:---------------|:---------------------:|:---------:|:--------:|
|game module |views|x|x|x|
|game module |_builtin|x|x|x|
|`otree.views.concrete`|`AdvanceSession`|||x|
|`otree.views.concrete`|`AssignVisitorToOpenSession`|x|x|x|
|`otree.views.concrete`|`AssignVisitorToOpenSessionMTurk`|x|x|x|
|`otree.views.concrete`|`DeleteSessions`|||x|
|`otree.views.concrete`|`InitializeParticipant`|x|x|x|
|`otree.views.concrete`|`MTurkLandingPage`|x|x|x|
|`otree.views.concrete`|`MTurkStart`|x|x|x|
|`otree.views.concrete`|`OutOfRangeNotification`|x|x|x|
|`otree.views.concrete`|`SessionExperimenterWaitUntilPlayersAreAssigned`|x|x|x|
|`otree.views.concrete`|`SetDefaultSession`|||x|
|`otree.views.concrete`|`ToggleArchivedSessions`|||x|
|`otree.views.concrete`|`UnsetDefaultSession`|||x|
|`otree.views.concrete`|`WaitUntilAssignedToGroup`|x|x|x|
|`otree.views.demo`|`CreateDemoSession`||x|x|
|`otree.views.demo`|`DemoIndex`||x|x|
|`otree.views.demo`|`SessionFullscreen`||x|x|
|`otree.views.admin`|`AdminHome`|||x|
|`otree.views.admin`|`CreateSession`|||x|
|`otree.views.admin`|`EditSessionProperties`|||x|
|`otree.views.admin`|`MTurkInfo`|||x|
|`otree.views.admin`|`PersistentLabURLs`|||x|
|`otree.views.admin`|`SessionDescription`|||x|
|`otree.views.admin`|`SessionMonitor`|||x|
|`otree.views.admin`|`SessionPayments`|||x|
|`otree.views.admin`|`SessionResults`|||x|
|`otree.views.admin`|`SessionStartLinks`|||x|
|`otree.views.admin`|`SessionTypesToCreate`|||x|
|`otree.views.admin`|`WaitUntilSessionCreated`|||x|
|`otree.views.mturk`|`PayMTurk`|||x|
|`otree.views.mturk`|`SessionCreateHit`|||x|
|`otree.views.export`|`ExportAppDocs`|||x|
|`otree.views.export`|`ExportCsv`|||x|
|`otree.views.export`|`ExportIndex`|||x|
