### ISSUE TITLE
django-idmap only works sometimes

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#330]
See the commented out line on `otree.models.session` line 259:

`# assert self is subsession.session`

If I uncomment it, `runtests.py` fails with about 16 `AssertionError`s. This should not happen because we are using `django-idmap`, which is supposed to solve the problem of duplicate model instances.

However, if I negate it:

`assert self is not subsession.session`

Then I also get 3 `AssertionErrors`. So, it seems the correct behavior only occurs some of the time.

**Comment by leliel12** [comment]
warning the assertion keyword is for test propuses if you run python -o or
--o the assertion lines is removed


On Sun, 7 Jun 2015 at 15:59 oTree-org <notifications@github.com> wrote:

> See the commented out line on otree.models.session line 259:
>
> # assert self is subsession.session
>
> If I uncomment it, runtests.py fails with about 16 AssertionErrors. This
> should not happen because we are using django-idmap, which is supposed to
> solve the problem of duplicate model instances.
>
> However, if I negate it:
>
> assert self is not subsession.session
>
> Then I also get 3 AssertionErrors. So, it seems the correct behavior only
> occurs some of the time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oTree-org/otree-core/issues/330>.
>
-- 

Juan BC (from phone)

**Comment by gregmuellegger** [comment]
@leliel12 IMO it is ok to use the `assert` statements in the code. It's not used to evaluate any code but to check on a constraint. You can use the assert statements anywhere to always be sure that the input or output of your code is within a valid range etc. Usually in production an assert should never raise an exception since it's checking for things that must not occur. But when it fails and raises an assertion error you get a really valuable information on what and where something has gone wrong. Like in this case, we want to check if the idmap library works for our cases. If it would work the assert would silently not do anything special. And if it fails, we know something is wrong very badly.

@oTree-org the issue is fixed. It was only occuring in the test runs and only if multiple tests where executed at once. The reason was that many tests create a new session model (which puts the instance into the idmap cache) with id 1 which are then wiped again after the test has finished. Then the next test also creates a session instance with id 1 and therefore collides with the existing idmap cache.

This only occurs with sqlite as sqlite gives new objects the next free ID. MySQL or Postgres would always increment the number for the next ID regardless of the current data in the DB. The fix for our testsuite is to always flush the idmap cache after each test run. You can comment in the assertion yourself again and check that it works for you as well.
