### ISSUE TITLE
Remove .bat files from launcher error reports

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#400]
Several people have told me they tried sending a launcher error report, but it was blocked by the mail server's virus filter, because the .zip contains .bat files. They seem to be generated by 

It seems to be caused by temp files being created with the .bat extension, defined [here](https://github.com/oTree-org/otree-launcher/blob/7ba54d450d08d3ce9bac24b87780cfe5985485a7/otree_launcher/cons.py#L172).

Can we modify this so that error reports don't contain .bat files?

**Comment by leliel12** [comment]
Because the bat files are necesary for evealute all the potential bugs, i fixed this bug by renaming all the **file.bat** files to **file_bat.txt** files, also in linux with the `sh`files the same transformation is done.

Fix here: https://github.com/oTree-org/otree-launcher/commit/7c35c0fcfe3b7895a2b2aa44026ad30a112ba056 (launcher 0.7.14)
