### ISSUE TITLE
Page "ajax" method

### ISSUE THREAD

**Issue by leliel12** [oTree-org/otree-core#469]
After some problems i currently have with ajax interaction with otree i sugest an `ajax` method inside every page view

This proposal try to replace #397 
## Rationale
- Only json can be send between client and server
- at start only post method is allowed
- Every page can be seamless connected to their `ajax`
## Example client side

If we are inside a page called `my_experiment.views.MyPage`

``` javascript
oTree.send(foo="faa", fee=[1,2,3]).on_return(function(data){
        ...
})
```

Internally the javascript `otree.send` method will call (without all session and participant data)

``` javascript
function oTreeAJAX(jQueryAJAX){
    var self = this;
    self.jQueryAJAX = jQueryAJAX;
    self.on_return = function(){};
    self.jQueryAJAX.always(function(data){
         self.on_return(jQuery.parseJSON(data)); 
    };
}
oTreeAJAX .prototype = {
    constructor: oTreeAJAX,
    on_return: function(fnc) {
         this.on_return = fnc;
    }
}
var jqa = $.post("my_experiment/MyPage/ajax", {foo: "faa", fee: [1,2,3]},  "json" )
var ota = new oTreeAJAX(jqa);
ota.on_return(function(data){
    ...
});
```
## Example Server Side

``` python
class MyPage(Page):

    def ajax(self, foo, fee):
        ...
       return {"foo": 123}
```
## Notes
1. http://javascriptissexy.com/oop-in-javascript-what-you-need-to-know/
2. https://api.jquery.com/jquery.post/

**Comment by leliel12** [comment]
@gregmuellegger @oTree-org  can you please give me an opinion about this?

I trying to give simple access to ajax to otree developers

**Comment by gregmuellegger** [comment]
I like the simplicity of this approach from the experiment author's perspective. Is this more used to partially load more data later on, or is this more meant to post form data before the next page is loaded?

A few random thoughts:

- I don't like the name `ajax` too much. However I also have a difficult time coming up with a better name. `ajax` is very generic, maybe it should be descriptive, depending on which usecases you have in mind.
- The `on_return` syntax is quite nice, however the default jQuery approach is usually to pass a `success` handler or something similiar to the first call, like:
```js
oTree.send({
  data: {foo: 123},
  success: function (result) {
    // do something
  }
});
```
If you want to go with the `on_return` syntax, you should consider using a promise. That's more or less a standard interface. Newer JavaScript implementations support promises that use a `then` method instead of the `on_return`, e.g.:
```js
oTree.send(...).then(the_on_return_handler_here);
```

jQuery supports promises as well, but there the `then` is called `done`. It's a mess that there are different naming schemes for promises, but I would say sticking with an existing one is better than inventing another one.

**Comment by leliel12** [comment]
i like the syntax of the promises. what is the "technical" diference inside
jquery of the promises vs the callbacks?

On Mon, 13 Jun 2016 at 15:28 Gregor Müllegger <notifications@github.com>
wrote:

> I like the simplicity of this approach from the experiment author's
> perspective. Is this more used to partially load more data later on, or is
> this more meant to post form data before the next page is loaded?
>
> A few random thoughts:
>
>    - I don't like the name ajax too much. However I also have a difficult
>    time coming up with a better name. ajax is very generic, maybe it
>    should be descriptive, depending on which usecases you have in mind.
>    - The on_return syntax is quite nice, however the default jQuery
>    approach is usually to pass a success handler or something similiar to
>    the first call, like:
>
> oTree.send({
>   data: {foo: 123},
>   success: function (result) {
>     // do something
>   }
> });
>
> If you want to go with the on_return syntax, you should consider using a
> promise. That's more or less a standard interface. Newer JavaScript
> implementations support promises that use a then method instead of the
> on_return, e.g.:
>
> oTree.send(...).then(the_on_return_handler_here);
>
> jQuery supports promises as well, but there the then is called done. It's
> a mess that there are different naming schemes for promises, but I would
> say sticking with an existing one is better than inventing another one.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/oTree-org/otree-core/issues/469#issuecomment-225667472>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AASQAnsRDyMG8DnRt5ISjpp_80K_qmRrks5qLaFdgaJpZM4Iq_ak>
> .
>
-- 

Juan BC (from phone)

**Comment by gregmuellegger** [comment]
The callback approach is super easy to understand. The promise approach is much more flexible and more orientated towards functional programming.

The promises are chainable, here is an example:

```
// Let's assume the server returns this object:
// { nameOfExperiment: "prisoners dilemma", participants: [...], sessionData: {...} }
var promise = oTree.send(...);
promise.then(function (response) {
  return response.participants;
}).then(function (participants) {
  updateParticipants(participants);
});
```

So here the first call to `then` returns a new promise. This promise contains the modified response. So the second then will receive the `response.pariticpants` value, not the complete `response` value. That makes it easier to reuse code. You could rewrite the code above like this:

```js
function getParticipantsFromResponse(response) { return response.participants; }

var promise = oTree.send(...);
promise.then(getParticipantsFromResponse).then(updateParticipants);
```

There are many good tutorials out there that explain promises much better than I can. They really are worth exploring as Promises are a native JS feature since ES2015.

**Comment by leliel12** [comment]
without the promise theory behind i i like the

otree.send(mesage).then(function(){})

approach.



On Mon, 13 Jun 2016 at 15:45 Gregor Müllegger <notifications@github.com>
wrote:

> The callback approach is super easy to understand. The promise approach is
> much more flexible and more orientated towards functional programming.
>
> The promises are chainable, here is an example:
>
> // Let's assume the server returns this object:
> // { nameOfExperiment: "prisoners dilemma", participants: [...], sessionData: {...} }
> var promise = oTree.send(...);
> promise.then(function (response) {
>   return response.participants;
> }).then(function (participants) {
>   updateParticipants(participants);
> });
>
> So here the first call to then returns a new promise. This promise
> contains the modified response. So the second then will receive the
> response.pariticpants value, not the complete response value. That makes
> it easier to reuse code. You could rewrite the code above like this:
>
> function getParticipantsFromResponse(response) { return response.participants; }
> var promise = oTree.send(...);promise.then(getParticipantsFromResponse).then(updateParticipants);
>
> There are many good tutorials out there that explain promises much better
> than I can. They really are worth exploring as Promises are a native JS
> feature since ES2015.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/oTree-org/otree-core/issues/469#issuecomment-225671873>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AASQAu7rvRiZ5tsLMrPyT3mbkV4MTGxYks5qLaUxgaJpZM4Iq_ak>
> .
>
-- 

Juan BC (from phone)

**Comment by solstice** [comment]
+

**Comment by bernieundert** [comment]
+1

**Comment by janvavra** [comment]
+1

**Comment by oTree-org** [comment]
Thanks for the feedback and suggestions; I know many people want support for AJAX/WebSockets and continuous time games. I plan to implement it at some point, but I am not ready at this point because (1) I am busy with existing development and maintenance, and (2) I don't have enough information about common use cases.

Implementing support for continuous-time games is a complex subject and there are many things to think about. If you are interested in this feature, you can help by sending me (via email or the oTree Google Group) a description of what kind of game/app you are looking to build, so i can better understand use cases & scenarios.

**Comment by oTree-org** [comment]
By the way, it's possible to build continuous time games right now with oTree by using Django functionality, but this requires researching how AJAX and WebSockets/channels are integrated with oTree, so I wouldn't recommended for less experienced users.
