### ISSUE TITLE
Add option for resetdb to ignore certain tables

### ISSUE THREAD

**Issue by mattboehm** [oTree-org/otree-core#495]
When I run `otree resetdb` it tries to query from (and then drop) any tables that already exist, including tables that are added by dbms_profiler and EDB. 

I think it would be nice to add an option to filter these tables out for the resetdb command. The underlying django `inspectdb` command already has a stealth option `table_name_filter` which is a function returning True if a table should be included and False if it should be ignored. I would suggest adding an option (either stealth or a documented argument) to `resetdb` called `ignore_table_prefixes`, which would be a pipe-delimited string of prefixes of tables that should be ignored by `resetdb`.

If you think this would be a useful feature, let me know and I can submit a pull request. Happy to take any suggestions you might have.

**Comment by oTree-org** [comment]
Hi, thanks for the suggestion. It's a sensible idea, but since it's a bit specialized, I think the best approach would be outside of otree-core as an extension. I recommend copying the resetdb source into your project, and putting it into one of your apps' management/commands/ directory. Then you can modify it. The source is here:

https://github.com/oTree-org/otree-core/blob/master/otree/management/commands/resetdb.py

It doesn't depend on any oTree internals, which makes it nicely self-contained. You could then even release that app on pypi and then reuse it as a dependency in various projects.

**Comment by mattboehm** [comment]
Thanks, I agree that that's a better solution =).
