### ISSUE TITLE
Potential memory leak issues?

### ISSUE THREAD

**Issue by weilu** [oTree-org/otree-core#528]
I have a otree deployment on heroku currently with 2 sessions each has 1000 participants. The total number of participants who visited in the last 2 days are only slightly over 200. At the peak of the peak, the app is handling 2-3 rps according to heroku's metrics. The app is running on a [standard-2x](https://devcenter.heroku.com/articles/dyno-types) web dyno and a standard-2x worker dyno. Worker dyno looks reasonably healthy, but the web dyno is constantly above its 1G memory quota and the response time is affected as a result. I noticed that every time immediately following a dyno restart (due to deployment or just heroku doing it) the memory usage drops back down and then over time slowly creeps back up:

![image](https://user-images.githubusercontent.com/412533/83573780-1a67a200-a4fa-11ea-98b6-1b39d32d1c23.png)

Before I upgrade to the next dyno tier, I just want to explore my options here. I saw you seem to have explored other ASGI options before: https://github.com/oTree-org/otree-core/blob/master/otree/management/commands/runprodserver1of2.py#L83 Both uvicorn and hypercorn have the option to auto restart workers after certain number of requests which would help with memory leak issues if there's any; however I don't think this is an option for daphne (cmiiw). Why did you decide on daphne? Is it worth exposing the choice of ASGI as an option for the command `otree runprodserver1of2`?

Any other suggestions on how I can manage this memory issue besides upgrading the dyno?

**Comment by oTree-org** [comment]
oTree uses daphne because that's the tried and true server for channels projects. You can test out another server if you want by modifying the 'web' line in your procfile. runprodserver1of2 is very simple, it basically just sets an env var and launches daphne. (The honcho stuff is only there for commands that subclass runprodserver1of2.)

Regarding the underlying memory issue, if you suspect there is an issue in oTree, I can investigate if you send me some minimal project that reproduces the issue or if you can reproduce the issue with oTree's sample games. Otherwise I can take a quick glance at your code, or you can try a profiler like pympler/tracemalloc.

**Comment by weilu** [comment]
Thanks! The project that I saw this issue was kind of a monster. I have another much smaller otree project going into production this coming week. I'll monitor and see if I observe similar memory usage pattern and come back with an update.

**Comment by weilu** [comment]
The smaller project uses much less memory (avg 200MB, max 300MB), similar pattern though – lowest after app start and increases over time until restart.
