### ISSUE TITLE
excel/csv export tools ignore field types

### ISSUE THREAD

**Issue by qwiglydee** [oTree-org/otree-core#561]
In excel file string fields are written without type/formatting and Excel auto-detects some of them as numbers.
In csv string fields are written without quotes, which again leads to wrong auto-detection.

Writing strings like "00001010000" (a digits matrix content) become numbers like 1010000

**Comment by oTree-org** [comment]
Thanks, you are right!

However, the tricky part is finding a good fix. From my research, this seems to be an Excel quirk, rather than a problem with how Python is writing the .csv files. Using QUOTE_ALL had no effect for me. I have found other workarounds but I have yet to find one I like (in my experience with Excel data formats, fixing one use case often breaks another). Anyway will keep this in mind.
