### ISSUE TITLE
session.config.real_world_currency_per_point is not a currency field

### ISSUE THREAD

**Issue by peterjc** [oTree-org/otree-core#568]
I have the following in ``settings.py``:

```
SESSION_CONFIG_DEFAULTS = dict(real_world_currency_per_point=0.05, participation_fee=5)
LANGUAGE_CODE = 'en'
REAL_WORLD_CURRENCY_CODE = 'GBP'
USE_POINTS = True
```

I am trying to use this in an HTML template:

> You will receive {{ session.config.participation_fee }} to thank you for your participation today. In addition to that, you will be paid a sum of money which depends on the results of the games. During the games we work in points. At the end of the experiment, your earnings in points will be converted into GBP at an exchange rate of {{ session.config.real_world_currency_per_point }} per point.

With oTree v5.2.8 that is rendered as:

> You will receive £5.00 to thank you for your participation today. In addition to that, you will be paid a sum of money which depends on the results of the games. During the games we work in points. At the end of the experiment, your earnings in points will be converted into GBP at an exchange rate of 0.05 per point.

So while ``participation_fee`` is treated as a currency field (giving ``£5.00``), ``real_world_currency_per_point`` is not (shown as ``0.05`` rather than ``£0.05``). This appears to be an oversight?

**Comment by oTree-org** [comment]
Thank you reporting. This is intentional. One reason for treating it as a float rather than real world currency is because of rounding. For example if you are using high point magnitudes, your real_world_currency_per_point might be like 0.00001,  which in most currencies would be rounded to 0.

Anyway think of it as an exchange rate. It doesn't necessarily need a unit attached to it. To display it in a template as a currency, you can use `{{ session.config.real_world_currency_per_point|cu }}`.
